# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test app on ${{ github.ref }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: echo ${{ secrets.DOT_ENV }} | base64 --decode > .env
      - run: npm run lint
      - run: npm run build
        env:
          CI: true
