# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test app on ${{ github.ref }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run lint
      - run: npm run build
        env:
          CI: true

  deploy-app:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy App
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install -g firebase-tools tslint typescript
      - run: npm ci
      - run: npm run build
      - run: firebase deploy --only hosting --non-interactive --token ${{ secrets.FIREBASE_DEPLOY_KEY }}
        env:
          CI: true
